///////////////////////////////////////////////////////////
//  Warrior.cs
//  Implementation of the Class Warrior
//  Generated by Enterprise Architect

///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace ApplicationNavigation.Model
{


    public class Warrior : PlayerCharacter
    {

        public Warrior()
        {

        }

        ~Warrior()
        {

        }

    }//end Warrior

}